#import <UIKit/UIKit.h>

@interface LGCustomIconGenerator2 : NSObject

+ (instancetype)sharedGenerator;

- (UIImage *)requestStyledImageForImage:(UIImage *)orig bundleID:(NSString *)bundleID;

- (UIImage *)requestIconImageWithBackgroundForImage:(UIImage *)orig bundleID:(NSString *)bundleID;

- (void)saveOriginalImage:(UIImage *)image forBundleID:(NSString *)bundleID;
- (UIImage *)originalImageForBundleID:(NSString *)bundleID;

- (void)clearCache;

- (void)clearDiskCache;

- (void)reloadDirectoryIndex;
- (NSString *)activePackDirectory;
- (NSString *)activePackId;
- (NSArray<NSString *> *)orderedPacksList;
- (NSString *)packDirectoryForId:(NSString *)packId;

- (UIImage *)generateDarkIconForImage:(UIImage *)image bundleID:(NSString *)bundleID;
- (UIImage *)generateClearIconForImage:(UIImage *)image bundleID:(NSString *)bundleID;
- (UIImage *)compositeGlyph:(UIImage *)glyph withBackgroundStyle:(NSString *)style isDarkTheme:(BOOL)isDarkTheme tintColor:(UIColor *)tintColor isAutoGenerated:(BOOL)isAutoGenerated drawSpecular:(BOOL)drawSpecular;
- (UIImage *)compositeGlyph:(UIImage *)glyph withBackgroundStyle:(NSString *)style isDarkTheme:(BOOL)isDarkTheme tintColor:(UIColor *)tintColor isAutoGenerated:(BOOL)isAutoGenerated drawSpecular:(BOOL)drawSpecular isStockArtwork:(BOOL)isStockArtwork;
- (UIImage *)applySpecularHighlightToImage:(UIImage *)image;
- (UIImage *)applySquircleMaskToImage:(UIImage *)image;
- (NSString *)specularStyle;
- (BOOL)isSpecularEnabled;
- (void)getSpecularStart:(CGPoint *)outStart end:(CGPoint *)outEnd forSize:(CGSize)size;

- (void)_resolveEffectiveStyle:(NSString **)outStyle isDarkTheme:(BOOL *)outIsDark;
- (UIImage *)_premadeIconForBundleID:(NSString *)bundleID style:(NSString *)style;
- (UIColor *)adjustedTintColorFromHex:(NSString *)hexString isDarkTheme:(BOOL)isDarkTheme;
- (UIImage *)generateDynamicIconForBundleID:(NSString *)bundleID style:(NSString *)style isDarkTheme:(BOOL)isDarkTheme;

- (UIImage *)fastCachedIconForBundleID:(NSString *)bundleID;
- (UIImage *)skeletonBackgroundForStyle:(NSString *)style isDarkTheme:(BOOL)isDarkTheme tintColor:(UIColor *)tintColor size:(CGSize)size scale:(CGFloat)scale;
- (UIImage *)skeletonBackgroundForBundleID:(NSString *)bundleID size:(CGSize)size scale:(CGFloat)scale;
- (void)requestIconAsyncForImage:(UIImage *)orig bundleID:(NSString *)bundleID completion:(void (^)(UIImage *styled))completion;
- (UIImage *)_upscaleImageIfNeeded:(UIImage *)image toSize:(CGSize)targetSize;

@end

